name: gaiaPi
on: 
  push:
    branches: main
   
  
jobs:
  gaiaPi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        run: |
          cd .pi
          bash build.sh
          
      - name: Compress
        run: xz -T $(nproc) full/images/gaia.img

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: sos
          path: full/images/gaia.img.xz
